name: CI

on: [ push, pull_request ]

jobs:
  ci:
    runs-on: [ self-hosted, Windows ]
    name: CI
    steps:
      - uses: actions/checkout@v3

      - name: Check CMake version
        run: cmake --version

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Generate CMake project
        run: cmake -D CMAKE_BUILD_TYPE=Release -S. -Bbuild -G Ninja

      - name: Build 64bit release DLL
        run: cmake --build ./build --config Release --target Terminus --

      - name: Check if DLL got built
        run: if (-Not (Test-Path -path "build/Terminus.dll")) {throw 1}

      - name: Rename DLL to Terminus-dev-{GITHUB_SHA}.dll
        run: |
          del Terminus-dev-*.dll
          ren Terminus.dll Terminus-dev-${{github.sha}}.dll
        working-directory: build/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: build/Terminus-dev-*.dll